baseURL = 'https://effulgent-halva-95c111.netlify.app/'
languageCode = 'en-us'
title = 'IT-Beratung, IT-Service Heidelberg, Mannheim, Ludwigshafen, Rhein-Neckar.'

# main menu
[menu] 
[[menu.nav]]
  identifier = "startseite"
  name = "Startseite"
  url = ""
  weight = 1

[[menu.nav]]
  identifier = "leistungen"
  name = "Leistungen"
  url = "it-diensleistungen"
  weight = 2

[[menu.nav]]
  identifier = "beratung"
  name = "Beratung"
  url = "it-diensleistungen/beratung/"
  parent = "leistungen"
  weight = 1

[[menu.nav]]
  identifier = "infrastruktur"
  name = "Infrastruktur"
  url = "it-diensleistungen/infrastruktur-technik/"
  parent = "leistungen"
  weight = 2

[[menu.nav]]
  identifier = "virtualisierung"
  name = "Virtualisierung"
  url = "it-diensleistungen/virtualisierung/"
  parent = "leistungen"
  weight = 3

[[menu.nav]]
  identifier = "telefonanlagen"
  name = "Telefonanlagen"
  url = "it-diensleistungen/ip-telefonanlage-voip/"
  parent = "leistungen"
  weight = 4

[[menu.nav]]
  identifier = "hosting"
  name = "Hosting"
  url = "it-diensleistungen/hosting/"
  parent = "leistungen"
  weight = 5

[[menu.nav]]
  identifier = "datensicherung"
  name = "Datensicherung"
  url = "it-diensleistungen/datensicherung"
  parent = "leistungen"
  weight = 6

[[menu.nav]]
  identifier = "systemsicherheit"
  name = "Systemsicherheit"
  url = "it-diensleistungen/systemsicherheit/"
  parent = "leistungen"
  weight = 7

[[menu.nav]]
  identifier = "leasing"
  name = "Leasing"
  url = "it-diensleistungen/leasing/"
  parent = "leistungen"
  weight = 8

[[menu.nav]]
  identifier = "datenrettung"
  name = "Datenrettung"
  url = "it-diensleistungen/datenrettung/"
  parent = "leistungen"
  weight = 9

[[menu.nav]]
  identifier = "notfall-service"
  name = "Notfall-Service"
  url = "it-diensleistungen/notfall-service/"
  parent = "leistungen"
  weight = 10

[[menu.nav]]
  identifier = "fernwartung"
  name = "Fernwartung"
  url = "it-diensleistungen/fernwartung/"
  parent = "leistungen"
  weight = 11


[[menu.nav]]
  identifier = "ueber-uns"
  name = "Ãœber uns"
  url = "ueber-uns"
  weight = 3

[[menu.nav]]
  identifier = "karriere"
  name = "Karriere"
  url = "karriere"
  weight = 4

[[menu.nav]]
  identifier = "erfolge"
  name = "Erfolge"
  url = "erfolgsgeschichten"
  weight = 5

[[menu.nav]]
  identifier = "kontakt"
  name = "Kontakt"
  url = "kontakt"
  weight = 6

